# Generated by Django 5.0.6 on 2024-05-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ris_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
